output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "/data2/yichaoxiong/data/VOCdevkit/onedet_cache"

train:
    dataset: "train"
    stdout: False
    gpus: "1"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 40000,60000] 
    lr_rates: [0.0005,0.001,0.002,0.02, 0.002,0.0002] 
    max_batches: 80200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [10000]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 16
    weights: ~ 

test:
    dataset: "test"
    stdout: True
    gpus: "3"
    nworkers: 8
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 16
    weights: "outputs/RegionXception/baseline/weights/backup.pt"

    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
